GET https://www.ttvn.nl/api/inschrijving/getAll HTTP/1.1
content-type: application/json
Accept: application/json
Database: ttest
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzUyNjMzNDgsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTYzNTM0OTc0OCwidXNlcmlkIjoiMzE5ODA0OCIsImRhdGFiYXNlIjoidHRlc3QiLCJyb2xlIjoiQlMsVEUsQUQiLCJmaXJzdG5hbWUiOiJXaW0iLCJsYXN0bmFtZSI6IktpZWxlbiIsImxpZG5yIjoiMjMifQ.uveJEAs_dZ50uPSh35cnFvNqJKmRaMMwJy5wKbwYvEI
###
POST  https://www.ttvn.nl/api/inschrijving/register HTTP/1.1
content-type: application/json
Accept: application/json
Database: ttest

{
  "Agenda_Id": "67",
  "Naam": "Piet",
  "Email": "wim_kielen@hotmail.com"
}
###
http://localhost:4200/#/inschrijven?evenement=eyAiZXZlbmVtZW50IjogNjcsICJsaWRuciI6IDIzIH0=
content-type: application/json
Accept: application/json
Database: ttest
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2Mjc0MTMwMjgsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTYyNzQ5OTQyOCwidXNlcmlkIjoiMzE5ODA0OCIsImRhdGFiYXNlIjoidHRlc3QiLCJyb2xlIjoiQlMsVEUsQUQiLCJmaXJzdG5hbWUiOiJXaW0iLCJsYXN0bmFtZSI6IktpZWxlbiIsImxpZG5yIjoiMjMifQ.U9o04CYziNMM_6oMToUgW74vnfEhTtmGJJ_JkQVQAaI
###
https://www.ttvn.nl/api/inschrijving/getsubscriptions?Id=2146
content-type: application/json
Accept: application/json
Database: ttest
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MzY2MzQyODgsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTY2ODE3MDI4OCwidXNlcmlkIjoiMzE5ODA0OCIsImRhdGFiYXNlIjoidHRlc3QiLCJyb2xlIjoiQlMsVEUsQUQiLCJmaXJzdG5hbWUiOiJXaW0iLCJsYXN0bmFtZSI6IktpZWxlbiIsImxpZG5yIjoiMjMifQ.eFWoV0yJU9k4P6nF7RHgz6JUOYjc6EgctTq13SVN4R0
