GET https://www.ttvn.nl/api/param/get?Id=Masterz
content-type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjE0OTQwNjcsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTYyMTU4MDQ2NywidXNlcmlkIjoiMzE5ODA0OCIsImRhdGFiYXNlIjoidHRlc3QiLCJyb2xlIjoiQlMsVEUsQUQiLCJmaXJzdG5hbWUiOiJXaW0iLCJsYXN0bmFtZSI6IktpZWxlbiIsImxpZG5yIjoiMjMifQ.vabfzoUWIWqia7GF8NiUAX7XW7SqWJdd7OVDPbp5NqU
###
GET https://www.ttvn.nl/api/param/GetAll
content-type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjE0OTQwNjcsImlzcyI6ImxvY2FsaG9zdCIsImV4cCI6MTYyMTU4MDQ2NywidXNlcmlkIjoiMzE5ODA0OCIsImRhdGFiYXNlIjoidHRlc3QiLCJyb2xlIjoiQlMsVEUsQUQiLCJmaXJzdG5hbWUiOiJXaW0iLCJsYXN0bmFtZSI6IktpZWxlbiIsImxpZG5yIjoiMjMifQ.vabfzoUWIWqia7GF8NiUAX7XW7SqWJdd7OVDPbp5NqU
