
POST https://www.ttvn.nl/api/signin.php HTTP/1.1
content-type: application/json
Accept: application/json
Database: ttest

{
    "userid": "3198048",
    "password": "3e84930f9e2769d6d71df43be7923c20",
    "database": "ttest",
    "keepsignedin": "false"
}

